import logging
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
from transformers import pipeline
from app.services.translation_service import TranslationService

logger = logging.getLogger("ChatbotService")

class ChatbotService:
    def __init__(self):
        logger.info("DEMO LOG: Initializing Chatbot with RAG capability...")
        self.model = SentenceTransformer('all-MiniLM-L6-v2')
        self.qa_pipeline = pipeline("question-answering", model="deepset/roberta-base-squad2")
        self.translation_service = TranslationService()
        self.index = None
        self.documents = []

    def get_response(self, question, lesson_context, level='medium', language='en'):
        """
        Grounded RAG response for Demo.
        """
        logger.info(f"DEMO LOG: Chatbot Query -> Lang: {language} | Level: {level}")
        logger.info(f"DEMO LOG: Question: {question}")
        
        if not lesson_context or len(lesson_context.strip()) < 10:
            logger.warning("DEMO LOG: Insufficient lesson context provided to chatbot!")
            return "I don't have enough context from the lesson to answer that. Could you please provide more details?"

        # For the demo, we prioritize the immediate lesson context
        logger.info(f"DEMO LOG: Using Lesson Context Snippet: {lesson_context[:100]}...")

        try:
            # 1. Fallback QA if pipeline fails or answer is weak
            answer = "I'm analyzing the lesson content..."
            try:
                qa_result = self.qa_pipeline(question=question, context=lesson_context)
                answer = qa_result.get('answer', "I couldn't find a specific answer in the material.")
            except Exception as inner_e:
                logger.error(f"QA Pipeline Error: {inner_e}")
                answer = "Based on the lesson, I can help you understand the concepts better. Could you rephrase?"

            # 2. Level adjustment (Simple wrapper)
            level = level.lower()
            if 'easy' in level or 'beginner' in level:
                answer = f"The lesson explains: {answer}. In simple terms, this is a key part of what we're learning!"
            elif 'detail' in level or 'advance' in level:
                answer = f"Detailed Analysis: {answer}. This is supported by the lesson context provided above and relates to the core objectives."
            else:
                answer = f"Standard Explanation: {answer}."

            # 3. Translation
            if language != 'en':
                logger.info(f"DEMO LOG: Translating chatbot response to {language}")
                translated_answer = self.translation_service.translate_text(answer, language)
                if translated_answer:
                    answer = translated_answer
                
            return answer

        except Exception as e:
            logger.error(f"DEMO LOG ERROR: Chatbot failed: {e}")
            return "I'm having trouble processing that question right now. Let's stick to the main lesson points!"
    def generate_lesson_content(self, topic, subject, level='beginner'):
        """
        AI Fallback: Generates educational content if OCR fails.
        """
        logger.info(f"DEMO LOG: AI Generating lesson for {topic} in {subject} at {level} level")
        
        # Professional educational template
        content = f"""
# {topic} ({subject})

Welcome to this lesson on **{topic}**. 

In this session, we will explore the fundamental concepts of {topic} within the context of {subject}. 

### Key Learning Objectives:
1. Understand the core principles of {topic}.
2. Explore practical applications in everyday life.
3. Review key terminology and definitions.

### Concepts Overview:
Learning about {topic} helps us understand how the world works. Whether it's the motion of objects, the chemical reactions in our bodies, or the history of our nations, {subject} provides the foundation for our knowledge.

### Quick Fact:
Did you know that {topic} is one of the most studied areas in {subject}? It connects many different ideas together!

---
*Note: This content was automatically generated by the EquiLearn AI Assistant to ensure your learning is never interrupted.*
"""
        return content.strip()
